use pocket_ic from crates.io
bitfinity-network/canister-sdk pull request #207
Opened 2024-02-14 13:52 UTC by ufoscout

2024-02-14 15:57 UTC, veeso requested changes

2024-02-14 15:57 UTC, veeso commented on Cargo.toml
> +pocket-ic = "2.2"
why not 3?

2024-02-14 15:58 UTC, veeso approved these changes

2024-02-14 16:24 UTC, ufoscout commented on Cargo.toml
> +pocket-ic = "2.2"
there's no 3

2024-02-15 05:14 UTC, F3kilo approved these changes

2024-02-15 06:48 UTC, merged