Revert "EPROD 653 define how to handle panics in the task scheduler"
bitfinity-network/canister-sdk pull request #209
Opened 2024-02-19 10:29 UTC by ufoscout

Reverts bitfinity-network/canister-sdk#202

2024-03-14 10:12 UTC, veeso requested changes

2024-03-14 10:12 UTC, veeso commented on ic-task-scheduler/src/task.rs
> +        Self {
these can just become Self::with_status

2024-03-14 15:07 UTC, veeso approved these changes

2024-03-19 12:23 UTC, itsyaasir approved these changes

2024-03-19 14:28 UTC, merged